import { type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode, useRef, useState } from 'react'
import { X, UploadCloud, LoaderCircle, CheckCircle2 } from 'lucide-react'
import { cn } from '@/lib/utils'

export function Button({className,variant='primary',size='md',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'|'coral'|'danger';size?:'sm'|'md'|'icon'}){
 const styles={primary:'bg-primary text-primary-foreground hover:bg-primary/90',secondary:'border border-border bg-card text-foreground hover:bg-muted',ghost:'text-muted-foreground hover:bg-muted hover:text-foreground',coral:'bg-accent text-accent-foreground hover:bg-accent/90',danger:'bg-destructive text-destructive-foreground'}
 const sizes={sm:'h-8 px-3 text-xs',md:'h-10 px-4 text-sm',icon:'size-9'}
 return <button className={cn('inline-flex shrink-0 items-center justify-center gap-2 rounded-lg font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50',styles[variant],sizes[size],className)} {...props}/>
}
export function Input(props:InputHTMLAttributes<HTMLInputElement>){return <input {...props} className={cn('h-10 w-full rounded-lg border border-input bg-card px-3 text-sm outline-none placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-ring/20',props.className)}/>}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:'success'|'warning'|'danger'|'teal'|'coral'|'neutral'}){const s={success:'bg-success-soft text-success',warning:'bg-warning-soft text-warning-ink',danger:'bg-destructive-soft text-destructive',teal:'bg-primary-soft text-primary',coral:'bg-accent-soft text-accent',neutral:'bg-muted text-muted-foreground'};return <span className={cn('inline-flex items-center rounded-full px-2.5 py-1 text-[11px] font-semibold',s[tone])}>{children}</span>}
export function Card({children,className}:{children:ReactNode;className?:string}){return <section className={cn('rounded-xl border border-border bg-card shadow-card',className)}>{children}</section>}
export function PageHeader({title,subtitle,actions}:{title:string;subtitle:string;actions?:ReactNode}){return <div className="mb-7 flex items-start justify-between gap-5"><div><h1 className="font-display text-3xl font-bold text-foreground">{title}</h1><p className="mt-1.5 text-sm text-muted-foreground">{subtitle}</p></div>{actions&&<div className="flex items-center gap-2">{actions}</div>}</div>}
export function Modal({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:ReactNode}){if(!open)return null;return <div className="fixed inset-0 z-50 grid place-items-center bg-overlay p-4" onMouseDown={onClose}><div role="dialog" aria-modal="true" className="w-full max-w-lg rounded-xl border border-border bg-card shadow-modal" onMouseDown={e=>e.stopPropagation()}><div className="flex items-center justify-between border-b border-border px-6 py-4"><h2 className="font-display text-lg font-bold">{title}</h2><Button variant="ghost" size="icon" aria-label="Close" onClick={onClose}><X className="size-4"/></Button></div><div className="p-6">{children}</div></div></div>}
export function FormField({label,children}:{label:string;children:ReactNode}){return <label className="grid gap-1.5 text-sm font-semibold text-foreground">{label}{children}</label>}
export function SelectBox({children,defaultValue,onChange}:{children:ReactNode;defaultValue?:string;onChange?:(v:string)=>void}){return <select defaultValue={defaultValue} onChange={e=>onChange?.(e.target.value)} className="h-10 rounded-lg border border-input bg-card px-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-ring/20">{children}</select>}
export function EmptyState({icon,title,body,action}:{icon:ReactNode;title:string;body:string;action?:ReactNode}){return <div className="grid min-h-64 place-items-center p-8 text-center"><div><div className="mx-auto mb-4 grid size-11 place-items-center rounded-full bg-primary-soft text-primary">{icon}</div><h3 className="font-display font-bold">{title}</h3><p className="mx-auto mt-1 max-w-sm text-sm text-muted-foreground">{body}</p>{action&&<div className="mt-5">{action}</div>}</div></div>}
export function FileUpload({accept,label,onComplete}:{accept:string;label:string;onComplete?:()=>void}){const ref=useRef<HTMLInputElement>(null);const [state,setState]=useState<'idle'|'loading'|'done'>('idle');const run=()=>{setState('loading');setTimeout(()=>{setState('done');onComplete?.()},1100)};return <div onClick={()=>ref.current?.click()} className="cursor-pointer rounded-xl border border-dashed border-primary/40 bg-primary-soft/40 p-8 text-center transition-colors hover:bg-primary-soft"><input ref={ref} className="hidden" type="file" accept={accept} onChange={run}/>{state==='loading'?<LoaderCircle className="mx-auto size-7 animate-spin text-primary"/>:state==='done'?<CheckCircle2 className="mx-auto size-7 text-success"/>:<UploadCloud className="mx-auto size-7 text-primary"/>}<p className="mt-3 text-sm font-semibold">{state==='loading'?'Processing file…':state==='done'?'File ready':label}</p><p className="mt-1 text-xs text-muted-foreground">Drag and drop, or click to browse</p></div>}
export function Skeleton({className}:{className?:string}){return <div className={cn('animate-pulse rounded-md bg-muted',className)}/>}
