/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as TranscriptsRouteImport } from './routes/transcripts'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as TranscriptsTranscriptIdRouteImport } from './routes/transcripts.$transcriptId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptsRoute = TranscriptsRouteImport.update({
  id: '/transcripts',
  path: '/transcripts',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => CampaignsRoute,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const TranscriptsTranscriptIdRoute = TranscriptsTranscriptIdRouteImport.update({
  id: '/$transcriptId',
  path: '/$transcriptId',
  getParentRoute: () => TranscriptsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/meetings': typeof MeetingsRoute
  '/transcripts': typeof TranscriptsRouteWithChildren
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/transcripts/$transcriptId': typeof TranscriptsTranscriptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/meetings': typeof MeetingsRoute
  '/transcripts': typeof TranscriptsRouteWithChildren
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/transcripts/$transcriptId': typeof TranscriptsTranscriptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/meetings': typeof MeetingsRoute
  '/transcripts': typeof TranscriptsRouteWithChildren
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/transcripts/$transcriptId': typeof TranscriptsTranscriptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/clients'
    | '/meetings'
    | '/transcripts'
    | '/campaigns/$campaignId'
    | '/clients/$clientId'
    | '/transcripts/$transcriptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns'
    | '/clients'
    | '/meetings'
    | '/transcripts'
    | '/campaigns/$campaignId'
    | '/clients/$clientId'
    | '/transcripts/$transcriptId'
  id:
    | '__root__'
    | '/'
    | '/campaigns'
    | '/clients'
    | '/meetings'
    | '/transcripts'
    | '/campaigns/$campaignId'
    | '/clients/$clientId'
    | '/transcripts/$transcriptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsRoute: typeof CampaignsRouteWithChildren
  ClientsRoute: typeof ClientsRouteWithChildren
  MeetingsRoute: typeof MeetingsRoute
  TranscriptsRoute: typeof TranscriptsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcripts': {
      id: '/transcripts'
      path: '/transcripts'
      fullPath: '/transcripts'
      preLoaderRoute: typeof TranscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof CampaignsRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/transcripts/$transcriptId': {
      id: '/transcripts/$transcriptId'
      path: '/$transcriptId'
      fullPath: '/transcripts/$transcriptId'
      preLoaderRoute: typeof TranscriptsTranscriptIdRouteImport
      parentRoute: typeof TranscriptsRoute
    }
  }
}

interface CampaignsRouteChildren {
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface TranscriptsRouteChildren {
  TranscriptsTranscriptIdRoute: typeof TranscriptsTranscriptIdRoute
}

const TranscriptsRouteChildren: TranscriptsRouteChildren = {
  TranscriptsTranscriptIdRoute: TranscriptsTranscriptIdRoute,
}

const TranscriptsRouteWithChildren = TranscriptsRoute._addFileChildren(
  TranscriptsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsRoute: CampaignsRouteWithChildren,
  ClientsRoute: ClientsRouteWithChildren,
  MeetingsRoute: MeetingsRoute,
  TranscriptsRoute: TranscriptsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
